-- MySQL Script generated by MySQL Workbench
-- Mon Jan 27 17:38:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fcs23a
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fcs23a` ;

-- -----------------------------------------------------
-- Schema fcs23a
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fcs23a` DEFAULT CHARACTER SET utf8 ;
USE `fcs23a` ;

-- -----------------------------------------------------
-- Table `fcs23a`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`job` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`job` (
  `job_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_title` VARCHAR(45) NOT NULL,
  `job_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcs23a`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`employee` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`employee` (
  `emp_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `job_id` TINYINT UNSIGNED NOT NULL,
  `emp_ssn` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `emp_fname` VARCHAR(15) NOT NULL,
  `emp_lname` VARCHAR(30) NOT NULL,
  `emp_dob` DATE NOT NULL,
  `emp_start_date` DATE NOT NULL,
  `emp_end_date` DATE NULL,
  `emp_salary` DECIMAL(8,2) NOT NULL,
  `emp_street` VARCHAR(30) NOT NULL,
  `emp_city` VARCHAR(20) NOT NULL,
  `emp_state` CHAR(2) NOT NULL,
  `emp_zip` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `emp_phone` BIGINT UNSIGNED NOT NULL,
  `emp_email` VARCHAR(100) NOT NULL,
  `emp_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `fk_employee_job1_idx` (`job_id` ASC) VISIBLE,
  UNIQUE INDEX `emp_ssn_UNIQUE` (`emp_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_employee_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `fcs23a`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcs23a`.`dependent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`dependent` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`dependent` (
  `dep_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `dep_added` DATE NOT NULL,
  `dep_ssn` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `dep_fname` VARCHAR(15) NOT NULL,
  `dep_lname` VARCHAR(30) NOT NULL,
  `dep_dob` DATE NOT NULL,
  `dep_relation` VARCHAR(20) NOT NULL,
  `dep_street` VARCHAR(30) NOT NULL,
  `dep_city` VARCHAR(20) NOT NULL,
  `dep_state` CHAR(2) NOT NULL,
  `dep_zip` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `dep_phone` BIGINT UNSIGNED NOT NULL,
  `dep_email` VARCHAR(100) NULL,
  `dep_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`dep_id`),
  INDEX `fk_dependent_employee_idx` (`emp_id` ASC) VISIBLE,
  UNIQUE INDEX `dep_ssn_UNIQUE` (`dep_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_dependent_employee`
    FOREIGN KEY (`emp_id`)
    REFERENCES `fcs23a`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcs23a`.`benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`benefit` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`benefit` (
  `ben_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ben_name` VARCHAR(45) NOT NULL,
  `ben_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`ben_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcs23a`.`plan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`plan` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`plan` (
  `pln_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NOT NULL,
  `ben_id` TINYINT UNSIGNED NOT NULL,
  `pln_type` ENUM('single', 'spouse', 'family') NOT NULL,
  `pln_cost` DECIMAL(6,2) UNSIGNED NOT NULL,
  `pln_election_date` DATE NOT NULL,
  `pln_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`pln_id`),
  INDEX `fk_plan_employee1_idx` (`emp_id` ASC) VISIBLE,
  INDEX `fk_plan_benefit1_idx` (`ben_id` ASC) VISIBLE,
  CONSTRAINT `fk_plan_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `fcs23a`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_benefit1`
    FOREIGN KEY (`ben_id`)
    REFERENCES `fcs23a`.`benefit` (`ben_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fcs23a`.`emp_hist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fcs23a`.`emp_hist` ;

CREATE TABLE IF NOT EXISTS `fcs23a`.`emp_hist` (
  `eht_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `emp_id` SMALLINT UNSIGNED NULL,
  `eht_date` DATETIME NOT NULL DEFAULT current_timestamp,
  `eht_type` ENUM('i', 'u', 'd') NOT NULL DEFAULT 'i',
  `eht_job_id` TINYINT UNSIGNED NOT NULL,
  `eht_emp_salary` DECIMAL(8,2) NOT NULL,
  `eht_usr_changed` VARCHAR(30) NOT NULL,
  `eht_reason` VARCHAR(45) NOT NULL,
  `eht_notes` VARCHAR(255) NULL,
  PRIMARY KEY (`eht_id`),
  INDEX `fk_emp_hist_employee1_idx` (`emp_id` ASC) VISIBLE,
  CONSTRAINT `fk_emp_hist_employee1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `fcs23a`.`employee` (`emp_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `fcs23a`.`job`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'CEO', NULL);
INSERT INTO `fcs23a`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'IT', NULL);
INSERT INTO `fcs23a`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Front Desk', NULL);
INSERT INTO `fcs23a`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Janitor', NULL);
INSERT INTO `fcs23a`.`job` (`job_id`, `job_title`, `job_notes`) VALUES (DEFAULT, 'Manager', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fcs23a`.`employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 2, 233329421, 'John', 'Berry', '1982-06-27', '2003-06-07', NULL, 92310, '916 Mosely', 'Tallahassee', 'fl', 32310, 8509382381, 'jbear@gmail.com', NULL);
INSERT INTO `fcs23a`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 3, 946553281, 'James', 'Bond', '1993-04-05', '2005-04-10', '2012-12-12', 65000, 'Elizabeth', 'Miami', 'FL', 30128, 3053940928, 'jbond@aol.com', NULL);
INSERT INTO `fcs23a`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 1, 392032933, 'The', 'Guy', '1900-01-001', '1912-06-06', NULL, 100000, 'thatstreet', 'New York', 'NY', 83920, 4090492837, 'him@gmail.com', 'The boss');
INSERT INTO `fcs23a`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 4, 382932038, 'Jim', 'Kronos', '1971-02-24', '2003-06-07', NULL, 92000, 'Lazy way', 'Key West', 'FL', 33041, 3059839203, 'jksebag@gmail.com', NULL);
INSERT INTO `fcs23a`.`employee` (`emp_id`, `job_id`, `emp_ssn`, `emp_fname`, `emp_lname`, `emp_dob`, `emp_start_date`, `emp_end_date`, `emp_salary`, `emp_street`, `emp_city`, `emp_state`, `emp_zip`, `emp_phone`, `emp_email`, `emp_notes`) VALUES (DEFAULT, 1, 903239372, 'Jacob', 'Johnston', '2005-04-17', '2006-12-11', '2018-12-12', 84000, 'Magnolia', 'Tallahassee', 'FL', 32320, 850293029, 'jjbjj@pb.com', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fcs23a`.`dependent`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 1, '2021-12-12', 098389281, 'Ben', 'Dander', '2003-06-04', 'Child', 'that street', 'This city', 'FL', 32201, 8392749283, 'hisemail@gmail.com', NULL);
INSERT INTO `fcs23a`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 1, '2021-12-12', 830122934, 'Mary', 'Jane', '1975-03-14', 'Spouse', 'that street', 'This city', 'FL', 32201, 8502393784, 'heremail@gmail.com', NULL);
INSERT INTO `fcs23a`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 3, '2012-07-09', 839473178, 'Josephine', 'Mongey', '1941-04-12', 'Spouse', 'Pinewood', 'Dublin', 'OH', 83103, 3922038274, 'jmongey@gmail.com', NULL);
INSERT INTO `fcs23a`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 5, '2006-09-09', 839438249, 'Tim', 'Benson', '2003-05-09', 'Child', 'Bamboo', 'Key West', 'FL', 33041, 3059302938, 'tmbfsu@fsu.edu', NULL);
INSERT INTO `fcs23a`.`dependent` (`dep_id`, `emp_id`, `dep_added`, `dep_ssn`, `dep_fname`, `dep_lname`, `dep_dob`, `dep_relation`, `dep_street`, `dep_city`, `dep_state`, `dep_zip`, `dep_phone`, `dep_email`, `dep_notes`) VALUES (DEFAULT, 2, '2008-05-15', 382032395, 'Jacob', 'Jameson', '2005-04-04', 'Child', 'Patricia', 'Tallahassee', 'FL', 32038, 3039285728, 'dgrock2838@gmail.com', 'rock');

COMMIT;


-- -----------------------------------------------------
-- Data for table `fcs23a`.`benefit`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, '401k', NULL);
INSERT INTO `fcs23a`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'Disability', NULL);
INSERT INTO `fcs23a`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'Dental', NULL);
INSERT INTO `fcs23a`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'Vision', NULL);
INSERT INTO `fcs23a`.`benefit` (`ben_id`, `ben_name`, `ben_notes`) VALUES (DEFAULT, 'Health', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fcs23a`.`plan`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 1, 1, 'Single', 5000, '2020-05-12', NULL);
INSERT INTO `fcs23a`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 1, 2, 'Spouse', 1000, '2021-06-07', NULL);
INSERT INTO `fcs23a`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 3, 1, 'Spouse', 2000, '2018-03-19', NULL);
INSERT INTO `fcs23a`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 5, 1, 'Family', 500, '2015-08-23', NULL);
INSERT INTO `fcs23a`.`plan` (`pln_id`, `emp_id`, `ben_id`, `pln_type`, `pln_cost`, `pln_election_date`, `pln_notes`) VALUES (DEFAULT, 2, 1, 'single', 500, '2018-03-12', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `fcs23a`.`emp_hist`
-- -----------------------------------------------------
START TRANSACTION;
USE `fcs23a`;
INSERT INTO `fcs23a`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 1, '2021-06-01', 'i', 2, 50000, 'test', 'promotion', NULL);
INSERT INTO `fcs23a`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 3, '2018-12-12', 'd', 3, 100000, 'test', 'fired', NULL);
INSERT INTO `fcs23a`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 1, '2023-04-18', 'u', 3, 120000, 'test', 'promotion', NULL);
INSERT INTO `fcs23a`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 4, '2004-12-18', 'd', 3, 12035, 'test', 'new plan', NULL);
INSERT INTO `fcs23a`.`emp_hist` (`eht_id`, `emp_id`, `eht_date`, `eht_type`, `eht_job_id`, `eht_emp_salary`, `eht_usr_changed`, `eht_reason`, `eht_notes`) VALUES (DEFAULT, 5, '2006-04-29', 'u', 3, 90834, 'test', 'promotion', NULL);

COMMIT;

